ALTER TABLE USER_PREFERENCES ADD ID NUMBER;

CREATE SEQUENCE user_pref_seq_temp;
UPDATE USER_PREFERENCES SET ID = user_pref_seq_temp.nextval;
DROP SEQUENCE user_pref_seq_temp;

ALTER TABLE USER_PREFERENCES MODIFY ID NUMBER NOT NULL;
ALTER TABLE USER_PREFERENCES ADD CONSTRAINT user_pref_pk PRIMARY KEY(id);